require 'active_record'

require 'racatt'


namespace 'tef' do
  namespace 'cuke_keeper' do

    def tef_env
      !ENV['TEF_ENV'].nil? ? ENV['TEF_ENV'].downcase : 'dev'
    end

    def tef_config
      !ENV['TEF_CUKE_KEEPER_DB_CONFIG'].nil? ? ENV['TEF_CUKE_KEEPER_DB_CONFIG'] : './config'
    end

    desc 'Migrate the database through scripts in db/migrate. Target specific version with VERSION=x'
    task migrate: :environment do
      ActiveRecord::Migrator.migrate('db/migrate', ENV['VERSION'] ? ENV['VERSION'].to_i : nil)
    end

    task :environment do
      ActiveRecord::Base.logger = nil
      db_config = YAML.load(File.open("#{tef_config}/database_#{tef_env}.yml"))
      ActiveRecord::Base.establish_connection(db_config)
      ActiveRecord::Base.table_name_prefix = "keeper_#{tef_env}_"
      ActiveRecord::Base.logger = Logger.new(File.open('database.log', 'a'))
    end


    Racatt.create_tasks

    task default: :test_everything
  end
end

task default: 'tef:cuke_keeper:test_everything'
