source 'http://rubygems.org'


# The gems that we use to test our stuff
def testing_gems
  gem 'rake', "~> 10.4"
  gem 'rspec', '~> 3.0'
  gem 'bundler', '~> 1.6'
  gem 'simplecov'
end

# The development (i.e. source code) versions of gems that are (or are needed by) our stuff
def dev_gems
  gem 'cucumber', '~> 2.0'
  gem 'mdf', path: '../mdf'
  gem 'tef-development', :path => '../../../tef/gems/tef-development'
end

# The real (i.e. installed on the machine) versions gems that are (or are needed by) our stuff
def test_gems
  gem 'cucumber', '~> 2.0'
  gem 'mdf'
  gem 'tef-development'
end

# Nothing new to see here.
def prod_gems
  test_gems
end

mode = ENV['BUNDLE_MODE'] || 'dev'
puts "Bundler mode: #{mode}"

case mode
  when 'dev'
    testing_gems
    dev_gems
  when 'test', 'prod'
    testing_gems
    test_gems
  when 'prod'
    prod_gems
  else
    raise(ArgumentError, "Unknown bundle mode: #{mode}. Must be one of dev/test/prod.")
end
