source 'http://rubygems.org'
source 'http://gems.github.com'


# The gems that we use to test our stuff
def testing_gems
  gem 'rake'
  gem 'rspec', '~> 3.0.0'
  gem 'rspec-mocks'
  gem 'cucumber'
  gem 'simplecov'
  gem 'racatt'
end

# The development (i.e. source code) versions of gems that are (or are needed by) our stuff
def dev_gems
  gem 'bunny'
  gem 'timers'
  gem 'process'

  # Dev mode has to explicitly include every needed gem dependency in the project in order to
  # be properly (i.e. recursively) loaded from source by Bundler
  gem 'task_runner', path: '../../../tef/gems/task_runner'
  gem 'cuke_runner', path: '../cuke_runner'
  gem 'tef-worker', path: '../../../tef/gems/tef-worker'
  gem 'tef-worker-cuke_worker', path: '../tef-worker-cuke_worker'
  gem 'tef-core', path: '../../../tef/gems/tef-core'
  gem 'tef-development', :path => '../../../tef/gems/tef-development'
end

# The real (i.e. installed on the machine) versions gems that are (or are needed by) our stuff
def test_gems
  gem 'bunny'
  gem 'timers'
  gem 'process'

  gem 'cuke_runner'
  gem 'tef-worker'
  gem 'tef-worker-cuke_worker'
  gem 'tef-development'
end

# Nothing new to see here.
def prod_gems
  test_gems
end

puts "Bundler mode: #{ENV['BUNDLE_MODE']}"
mode = ENV['BUNDLE_MODE']

case mode
  when 'dev'
    testing_gems
    dev_gems
  when 'test', 'prod'
    testing_gems
    test_gems
  when 'prod'
    prod_gems
  else
    raise(ArgumentError, "Unknown bundle mode: #{mode}. Must be one of dev/test/prod.")
end
