require 'racatt'


namespace 'tef' do
  namespace 'worker' do
    namespace 'cuke_worker' do

      Racatt.create_tasks

      task default: 'tef:worker:cuke_worker:test_everything'
    end
  end
end

task default: 'tef:worker:cuke_worker:test_everything'
